pipeline {
    agent any

    environment {
        SONARQUBE_TOKEN = 'squ_e59ba776f94d86c62455712e5121c725a5916ba1'
        SONARQUBE_SERVER = 'http://localhost:9999'
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-credentials')
    }

    tools {
        maven 'mvn'
    }

    stages {
        stage('Checkout') {
            steps {
                dir('CO-SCHOOL-SPRING') {
                    bat 'git branch: "jenkins", url: "https://github.com/oussamacharafi99/CO-SCHOOL.git"'
                    bat 'dir'
                }
            }
        }

        stage('Build and Test') {
            steps {
                dir('CO-SCHOOL-SPRING') {
                    bat 'mvn clean package'
                    bat 'dir'
                    bat 'mvn test'
                    bat 'dir'
                }
            }
        }

        stage('CO-SCHOOL-SPRING') {
            steps {
                dir('./') {
                    script {
                        def scannerHome = tool 'SonarQubeScanner'
                        bat "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=co-school -Dsonar.sources=. -Dsonar.host.url=${SONARQUBE_SERVER} -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.java.binaries=target/classes"
                    }
                    bat 'dir'
                }
            }
        }

        stage('Build Docker Images & Push') {
            steps {
                dir('CO-SCHOOL-SPRING') {
                    script {
                        def dockerImage = docker.build("oussamacharafi/co-school-repo:${env.TAG_VERSION ?: 'latest'}")
                        docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                            dockerImage.push()
                        }
                    }
                    bat 'dir'
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                dir('CO-SCHOOL-SPRING') {
                    bat 'docker-compose up -d'
                    bat 'dir'
                }
            }
        }
    }
}
